[phases.install]
commands = ["apt-get update && apt-get install -y caddy"]

[phases.build]
commands = ["npm install", "npm run build"]

[start]
cmd = "caddy file-server --root ./dist --listen :${PORT}"

