[ses.install]
commands = ["apt-get update && apt-get install -y caddy"]

[phases.build]
commands = ["npm install", "npm run build"]

[phases.start]
commands = ["caddy file-server --root ./dist --listen :${PORT}"]

