[phases.install]
commands = [
    "apt-get update",
    "apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl",
    "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg",
    "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list",
    "apt-get update",
    "apt-get install -y caddy"
]

[phases.build]
commands = ["npm install", "npm run build"]

[start]
cmd = "caddy file-server --root ./dist --listen :${PORT}"

